-- Flyway baseline for fresh FlipBot installations at schema version 35.
--
-- Existing installations keep their V1..V35 history unchanged. On a new
-- database Flyway can start from this complete schema instead of relying on
-- Hibernate ddl-auto=update to create the JPA tables before the old ALTER-based
-- migrations run.
--
-- The table/column model is based on a PostgreSQL 17 schema generated by the
-- current Hibernate mappings. Database-only invariants from V1..V35 are kept
-- explicitly below (checks, indexes, cascades and the durable marketplace claim).

CREATE TABLE bot (
    market_stats_observer BOOLEAN NOT NULL DEFAULT FALSE,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    name VARCHAR(255),
    password VARCHAR(255),
    status VARCHAR(255),
    CONSTRAINT bot_status_check
        CHECK (status IN ('RUNNING', 'STOPPED')),
    CONSTRAINT uk_bot_email
        UNIQUE (email)
);

CREATE TABLE bot_configuration (
    auto_raise_offer_to_vinted_minimum BOOLEAN NOT NULL DEFAULT FALSE,
    daily_negotiation_budget INTEGER,
    max_automatic_offer NUMERIC(38,2),
    max_price NUMERIC(38,2),
    min_price NUMERIC(38,2),
    bot_id BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand VARCHAR(255),
    marketplace VARCHAR(255),
    model VARCHAR(255),
    search_query VARCHAR(255),
    target_mode VARCHAR(255) NOT NULL DEFAULT 'VINTED_MODEL',

    CONSTRAINT uk_bot_configuration_bot
        UNIQUE (bot_id),
    CONSTRAINT fk_bot_configuration_bot
        FOREIGN KEY (bot_id) REFERENCES bot(id),
    CONSTRAINT bot_configuration_marketplace_check
        CHECK (
            marketplace IN (
                'TEST_PLATFORM',
                'VINTED',
                'OLX',
                'ALLEGRO'
            )
        ),
    CONSTRAINT bot_configuration_target_mode_check
        CHECK (target_mode IN ('VINTED_MODEL', 'SEARCH_QUERY'))
);

CREATE TABLE bot_category_path (
    path_index INTEGER NOT NULL,
    configuration_id BIGINT NOT NULL,
    category VARCHAR(255),

    CONSTRAINT bot_category_path_pkey
        PRIMARY KEY (path_index, configuration_id),
    CONSTRAINT bot_category_path_path_index_check
        CHECK (path_index >= 0),
    CONSTRAINT fk_bot_category_path_configuration
        FOREIGN KEY (configuration_id) REFERENCES bot_configuration(id)
);

CREATE UNIQUE INDEX uk_bot_category_path_position
    ON bot_category_path(configuration_id, path_index);

CREATE TABLE dictionary_brand (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_dictionary_brand_name UNIQUE (name)
);

CREATE TABLE dictionary_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path VARCHAR(1000) NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_dictionary_category_path UNIQUE (path)
);

CREATE TABLE dictionary_model (
    expected_resale_price NUMERIC(38,2),
    market_max_price NUMERIC(38,2),
    market_min_price NUMERIC(38,2),
    proposed_offer_price NUMERIC(38,2),
    brand_id BIGINT NOT NULL,
    category_id BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_mode VARCHAR(32) NOT NULL DEFAULT 'VINTED_MODEL',
    name VARCHAR(255) NOT NULL,

    CONSTRAINT uk_dictionary_model_brand_name
        UNIQUE (brand_id, name),
    CONSTRAINT fk_dictionary_model_brand
        FOREIGN KEY (brand_id) REFERENCES dictionary_brand(id),
    CONSTRAINT fk_dictionary_model_category
        FOREIGN KEY (category_id) REFERENCES dictionary_category(id),
    CONSTRAINT dictionary_model_target_mode_check
        CHECK (target_mode IN ('VINTED_MODEL', 'SEARCH_QUERY')),
    CONSTRAINT ck_dictionary_model_proposed_offer_price
        CHECK (proposed_offer_price IS NULL OR proposed_offer_price > 0),
    CONSTRAINT ck_dictionary_model_expected_resale_price
        CHECK (expected_resale_price IS NULL OR expected_resale_price > 0),
    CONSTRAINT chk_dictionary_model_market_min_price_positive
        CHECK (market_min_price IS NULL OR market_min_price > 0),
    CONSTRAINT chk_dictionary_model_market_max_price_positive
        CHECK (market_max_price IS NULL OR market_max_price > 0),
    CONSTRAINT chk_dictionary_model_market_price_range
        CHECK (
            market_min_price IS NULL
            OR market_max_price IS NULL
            OR market_min_price <= market_max_price
        )
);

CREATE INDEX idx_dictionary_model_category_id
    ON dictionary_model(category_id);

CREATE TABLE listing (
    awaiting_seller_response BOOLEAN NOT NULL,
    current_price NUMERIC(38,2) NOT NULL,
    current_step INTEGER NOT NULL,
    history_hidden BOOLEAN NOT NULL DEFAULT FALSE,
    original_price NUMERIC(38,2) NOT NULL,
    bot_id BIGINT NOT NULL,
    current_step_started_at TIMESTAMP(6) WITHOUT TIME ZONE,
    decision_at TIMESTAMP(6) WITHOUT TIME ZONE,
    formal_response_detected_at TIMESTAMP(6) WITHOUT TIME ZONE,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    read_detected_at TIMESTAMP(6) WITHOUT TIME ZONE,
    seller_activity_at TIMESTAMP(6) WITHOUT TIME ZONE,
    conversation_url VARCHAR(1000),
    url VARCHAR(1000) NOT NULL,
    conversation_id VARCHAR(255),
    formal_response_fingerprint VARCHAR(255),
    listing_id VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,

    CONSTRAINT fk_listing_bot
        FOREIGN KEY (bot_id) REFERENCES bot(id),
    CONSTRAINT uk_listing_bot_marketplace
        UNIQUE (bot_id, listing_id),
    CONSTRAINT listing_status_check
        CHECK (
            status IN (
                'DISCOVERED',
                'NEGOTIATING',
                'ACTION_REQUIRED',
                'SKIPPED_OFFER_TOO_LOW',
                'SKIPPED_OUTSIDE_PRICE_RANGE',
                'SKIPPED_CANNOT_NEGOTIATE',
                'SKIPPED_TARGET_MISMATCH',
                'SKIPPED_ALREADY_NEGOTIATED',
                'SKIPPED_BY_USER',
                'UNAVAILABLE',
                'CONTACT_UNAVAILABLE',
                'REJECTED',
                'EXPIRED',
                'PURCHASED',
                'FINISHED'
            )
        )
);

CREATE TABLE negotiation_step (
    counter_offer_default_wait_hours INTEGER,
    max_accepted_counter_offer NUMERIC(38,2),
    offer_price NUMERIC(38,2),
    read_wait_hours INTEGER NOT NULL DEFAULT 3,
    rejection_wait_hours INTEGER,
    step_number INTEGER,
    unread_wait_hours INTEGER NOT NULL DEFAULT 48,
    configuration_id BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    counter_offer_default_action VARCHAR(40) NOT NULL,
    rejection_action VARCHAR(40) NOT NULL,
    message VARCHAR(1000),

    CONSTRAINT fk_negotiation_step_configuration
        FOREIGN KEY (configuration_id) REFERENCES bot_configuration(id),
    CONSTRAINT negotiation_step_counter_offer_default_action_check
        CHECK (
            counter_offer_default_action IN (
                'NEXT_STEP_NOW',
                'WAIT_BEFORE_NEXT_STEP'
            )
        ),
    CONSTRAINT negotiation_step_rejection_action_check
        CHECK (
            rejection_action IN (
                'NEXT_STEP_NOW',
                'WAIT_BEFORE_NEXT_STEP'
            )
        ),
    CONSTRAINT negotiation_step_read_wait_hours_check
        CHECK (read_wait_hours BETWEEN 1 AND 720),
    CONSTRAINT negotiation_step_unread_wait_hours_check
        CHECK (unread_wait_hours BETWEEN 1 AND 720)
);

CREATE TABLE negotiation_step_counter_offer_rule (
    minimum_discount_percent NUMERIC(7,3) NOT NULL,
    rule_index INTEGER NOT NULL,
    wait_hours INTEGER,
    negotiation_step_id BIGINT NOT NULL,
    reaction_action VARCHAR(40) NOT NULL,

    CONSTRAINT negotiation_step_counter_offer_rule_pkey
        PRIMARY KEY (rule_index, negotiation_step_id),
    CONSTRAINT fk_negotiation_step_counter_offer_rule_step
        FOREIGN KEY (negotiation_step_id)
            REFERENCES negotiation_step(id)
            ON DELETE CASCADE,
    CONSTRAINT negotiation_step_counter_offer_rule_reaction_action_check
        CHECK (
            reaction_action IN (
                'NEXT_STEP_NOW',
                'WAIT_BEFORE_NEXT_STEP'
            )
        ),
    CONSTRAINT negotiation_step_counter_offer_rule_rule_index_check
        CHECK (rule_index >= 0)
);

CREATE UNIQUE INDEX uk_negotiation_step_counter_rule_position
    ON negotiation_step_counter_offer_rule(negotiation_step_id, rule_index);

CREATE TABLE bot_command (
    bot_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL,
    processed_at TIMESTAMP(6) WITH TIME ZONE,
    status VARCHAR(50) NOT NULL,
    type VARCHAR(50) NOT NULL,
    error_message VARCHAR(1000),

    CONSTRAINT fk_bot_command_bot
        FOREIGN KEY (bot_id)
            REFERENCES bot(id)
            ON DELETE CASCADE,
    CONSTRAINT fk_bot_command_listing
        FOREIGN KEY (listing_id)
            REFERENCES listing(id)
            ON DELETE CASCADE,
    CONSTRAINT bot_command_status_check
        CHECK (
            status IN (
                'PENDING',
                'PROCESSING',
                'COMPLETED',
                'FAILED'
            )
        ),
    CONSTRAINT bot_command_type_check
        CHECK (type = 'OPEN_CONVERSATION')
);

CREATE INDEX idx_bot_command_bot_status
    ON bot_command(bot_id, status, id);

CREATE TABLE daily_offer_quota (
    usage_date DATE NOT NULL,
    used_count INTEGER NOT NULL DEFAULT 0,
    bot_id BIGINT NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    CONSTRAINT fk_daily_offer_quota_bot
        FOREIGN KEY (bot_id)
            REFERENCES bot(id)
            ON DELETE CASCADE,
    CONSTRAINT uk_daily_offer_quota_bot_date
        UNIQUE (bot_id, usage_date),
    CONSTRAINT chk_daily_offer_quota_used_count
        CHECK (used_count >= 0)
);

CREATE TABLE bot_runtime_state (
    consecutive_failures INTEGER NOT NULL DEFAULT 0,
    worker_slot INTEGER,
    bot_id BIGINT PRIMARY KEY,
    last_run_duration_ms BIGINT,
    last_run_finished_at TIMESTAMP(6) WITH TIME ZONE,
    last_run_started_at TIMESTAMP(6) WITH TIME ZONE,
    next_run_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error TEXT,
    runtime_status VARCHAR(255) NOT NULL,

    CONSTRAINT fk_bot_runtime_state_bot
        FOREIGN KEY (bot_id)
            REFERENCES bot(id)
            ON DELETE CASCADE,
    CONSTRAINT bot_runtime_state_runtime_status_check
        CHECK (
            runtime_status IN (
                'IDLE',
                'QUEUED',
                'WORKING',
                'COOLDOWN',
                'ERROR'
            )
        ),
    CONSTRAINT chk_bot_runtime_state_failures
        CHECK (consecutive_failures >= 0),
    CONSTRAINT chk_bot_runtime_state_duration
        CHECK (last_run_duration_ms IS NULL OR last_run_duration_ms >= 0)
);

CREATE INDEX idx_bot_runtime_state_status
    ON bot_runtime_state(runtime_status);

CREATE INDEX idx_bot_runtime_state_next_run_at
    ON bot_runtime_state(next_run_at);

CREATE TABLE real_action_guard (
    step_number INTEGER NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL,
    request_id UUID NOT NULL,
    action_type VARCHAR(32) NOT NULL,

    CONSTRAINT fk_real_action_guard_listing
        FOREIGN KEY (listing_id)
            REFERENCES listing(id)
            ON DELETE CASCADE,
    CONSTRAINT uk_real_action_guard_listing
        UNIQUE (listing_id),
    CONSTRAINT uk_real_action_guard_request
        UNIQUE (request_id),
    CONSTRAINT real_action_guard_action_type_check
        CHECK (action_type IN ('FIRST_OFFER', 'NEXT_STEP')),
    CONSTRAINT ck_real_action_guard_step_number
        CHECK (step_number > 0)
);

CREATE INDEX idx_real_action_guard_created_at
    ON real_action_guard(created_at);

CREATE TABLE real_action_audit (
    offer_price NUMERIC(38,2),
    step_number INTEGER NOT NULL,
    backend_listing_id BIGINT NOT NULL,
    bot_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    request_id UUID NOT NULL,
    action_type VARCHAR(32) NOT NULL,
    message_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    outcome VARCHAR(32) NOT NULL,
    failure_reason VARCHAR(1000),
    conversation_id VARCHAR(255),
    marketplace_listing_id VARCHAR(255) NOT NULL,

    CONSTRAINT uk_real_action_audit_request
        UNIQUE (request_id),
    CONSTRAINT real_action_audit_action_type_check
        CHECK (action_type IN ('FIRST_OFFER', 'NEXT_STEP')),
    CONSTRAINT ck_real_action_audit_step_number
        CHECK (step_number > 0),
    CONSTRAINT ck_real_action_audit_offer_price
        CHECK (offer_price IS NULL OR offer_price > 0),
    CONSTRAINT real_action_audit_outcome_check
        CHECK (outcome IN ('CONFIRMED', 'AMBIGUOUS')),
    CONSTRAINT real_action_audit_message_status_check
        CHECK (message_status IN ('CONFIRMED', 'FAILED', 'UNKNOWN'))
);

CREATE INDEX idx_real_action_audit_bot_created
    ON real_action_audit(bot_id, created_at DESC);

CREATE INDEX idx_real_action_audit_marketplace_listing
    ON real_action_audit(marketplace_listing_id);

CREATE INDEX idx_real_action_audit_backend_listing
    ON real_action_audit(backend_listing_id);

CREATE TABLE market_model_scan_state (
    baseline_offer_count INTEGER,
    last_scan_complete BOOLEAN NOT NULL DEFAULT FALSE,
    baseline_complete_at TIMESTAMP(6) WITHOUT TIME ZONE,
    initialized_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    last_scan_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    last_successful_scan_at TIMESTAMP(6) WITHOUT TIME ZONE,
    model_id BIGINT PRIMARY KEY,

    CONSTRAINT fk_market_model_scan_state_model
        FOREIGN KEY (model_id)
            REFERENCES dictionary_model(id)
            ON DELETE CASCADE,
    CONSTRAINT ck_market_model_scan_state_baseline_offer_count_non_negative
        CHECK (baseline_offer_count IS NULL OR baseline_offer_count >= 0)
);

CREATE TABLE market_listing_observation (
    baseline BOOLEAN NOT NULL DEFAULT FALSE,
    first_seen_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_seen_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    model_id BIGINT NOT NULL,
    marketplace_listing_id VARCHAR(255) NOT NULL,

    CONSTRAINT fk_market_listing_observation_model
        FOREIGN KEY (model_id)
            REFERENCES dictionary_model(id)
            ON DELETE CASCADE,
    CONSTRAINT uk_market_listing_observation_model_listing
        UNIQUE (model_id, marketplace_listing_id)
);

CREATE INDEX idx_market_listing_observation_model_first_seen
    ON market_listing_observation(model_id, first_seen_at);

CREATE INDEX idx_market_listing_observation_model_last_seen
    ON market_listing_observation(model_id, last_seen_at);

CREATE TABLE price_probe (
    probe_price NUMERIC(19,2) NOT NULL,
    reference_offer_price NUMERIC(19,2) NOT NULL,
    claimed_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    completed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    probe_bot_id BIGINT NOT NULL,
    source_listing_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    failure_reason VARCHAR(1000),
    message VARCHAR(1000) NOT NULL,

    CONSTRAINT fk_price_probe_bot
        FOREIGN KEY (probe_bot_id)
            REFERENCES bot(id)
            ON DELETE CASCADE,
    CONSTRAINT fk_price_probe_source_listing
        FOREIGN KEY (source_listing_id)
            REFERENCES listing(id)
            ON DELETE CASCADE,
    CONSTRAINT uk_price_probe_bot_listing
        UNIQUE (probe_bot_id, source_listing_id),
    CONSTRAINT price_probe_status_check
        CHECK (
            status IN (
                'CLAIMED',
                'SENT',
                'FAILED',
                'UNKNOWN',
                'CANCELLED'
            )
        )
);

CREATE INDEX idx_price_probe_source_listing
    ON price_probe(source_listing_id);

CREATE INDEX idx_price_probe_bot_status
    ON price_probe(probe_bot_id, status);

CREATE TABLE marketplace_negotiation_claim (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marketplace VARCHAR(64) NOT NULL,
    marketplace_listing_id VARCHAR(255) NOT NULL,
    owner_bot_id BIGINT NOT NULL,
    owner_listing_id BIGINT NOT NULL,
    request_id UUID,
    claimed_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at TIMESTAMP(6) WITHOUT TIME ZONE,

    CONSTRAINT uk_marketplace_negotiation_claim
        UNIQUE (marketplace, marketplace_listing_id)
);

CREATE INDEX idx_marketplace_negotiation_claim_owner
    ON marketplace_negotiation_claim(owner_bot_id, owner_listing_id);

CREATE INDEX idx_marketplace_negotiation_claim_unconfirmed_owner
    ON marketplace_negotiation_claim(owner_bot_id)
    WHERE confirmed_at IS NULL;

INSERT INTO bot (
    name,
    email,
    password,
    status,
    market_stats_observer
)
SELECT
    'Anonymous Market Observer',
    NULL,
    NULL,
    'STOPPED',
    TRUE
WHERE NOT EXISTS (
    SELECT 1
    FROM bot
    WHERE market_stats_observer = TRUE
);
