CREATE TABLE daily_offer_quota
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    bot_id BIGINT NOT NULL,

    usage_date DATE NOT NULL,

    used_count INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT fk_daily_offer_quota_bot
        FOREIGN KEY (bot_id)
            REFERENCES bot(id)
            ON DELETE CASCADE,

    CONSTRAINT uk_daily_offer_quota_bot_date
        UNIQUE (bot_id, usage_date),

    CONSTRAINT chk_daily_offer_quota_used_count
        CHECK (used_count >= 0)
);