spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/flipbot_pr74"
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 33

  web:
    error:
      include-stacktrace: never
      include-exception: false

server:
  port: 8081
